resolver: lts-12.3

packages:
- .

extra-deps:
- normaldistribution-1.1.0.3
- primitive-0.6.1.1

- git: https://github.com/adscib/monad-bayes
  commit: 647ba7cb5a98ae028600f3d828828616891b40fb
- git: https://github.com/Haskell-mouse/repa-linear-algebra
  commit: 0cf2036e4423a14bbaf404e89bdd8f7c7321021d

extra-lib-dirs:
 - /usr/lib
